#!/usr/bin/perl
use strict;
use File::Basename;

my $CONTENT = "";
my $COMMENT = "";
my $EXECUTABLE = 0;

my $FILE = "library$ENV{PATH_INFO}";
if (-f $FILE) {
    $CONTENT = `/opt/spang/bin/spang mbgd ./$FILE -r /opt/spang/etc/prefix,/opt/user_prefix -q`;
    if ($CONTENT =~ s/^(# .*\n)//m) {
    # if ($CONTENT =~ s/^# (.*\n)//m) {
	$COMMENT = $1;
    }
    # $CONTENT =~ s/^#\S.*\n//mg;
    $CONTENT =~ s/^\s*#.*\n//mg;
    if ($COMMENT) {
    	$CONTENT = $COMMENT . "\n" . $CONTENT;
    }
    $EXECUTABLE = 1;
} elsif (-f "$FILE.rq") {
    $CONTENT = `cat $FILE.rq`;
    $EXECUTABLE = 0;
}

my $DIR = dirname $FILE;
my $BASENAME = basename $FILE;
$BASENAME =~ s/.rq$//;
my %KEY_VAL = ();
parse_ini_file("$DIR/index.ini", \%KEY_VAL);

if ($ENV{HTTP_ACCEPT} =~ /^text\/html/) {
    print "Content-type: text/html\n\n";

print <<HERE;
<!DOCTYPE html>
<html>
<head>
<title>SPARQL query</title>
<link href="/css/common.css" rel="stylesheet">
<link rel="stylesheet" href="/codemirror-5.30.0/lib/codemirror.css">
<script src="/codemirror-5.30.0/lib/codemirror.js"></script>
<script src="/codemirror-5.30.0/mode/sparql/sparql.js"></script>
<style>.CodeMirror {border-top: 1px solid black; border-bottom: 1px solid black;}</style>
</head>

<body>
<script type="text/javascript" src="https://dbcls.rois.ac.jp/DBCLS-common-header-footer/common-header-and-footer/script/common-header-and-footer.js" style="display: block" id="common-header-and-footer__script"></script>
<div class="content_wrapper_wide">

<div class="small">
<a href='/' class='link_title'>SPANG</a> >> <a href='/library' class='link_title'>Library</a> >> <a href='/$DIR' class='link_title'>$KEY_VAL{title}</a> >> $BASENAME
</div>
<h2>Execute SPARQL query</h2>
HERE

    if ($EXECUTABLE) {
	print '<form>';
	# print "Server: $KEY_VAL{title} ( $KEY_VAL{endpoint} ) ";
	print "Server: $KEY_VAL{title} ( <a href='$KEY_VAL{endpoint}'>$KEY_VAL{endpoint}</a> ) ";
	print '<br><br>';
	# print "Query: $COMMENT";
	# print '<br><br>';
    }
    print '<textarea id="code" name="code">';
    print $CONTENT;
    print '</textarea>';
    if ($EXECUTABLE) {
	print '</form>';
	print '<br>';
	print '<button type="button" onclick="iq();">Exec</button> ';
    }

    print '<script>';
    print 'var editor = CodeMirror.fromTextArea(document.getElementById("code"), {mode: "application/sparql-query"});';
    # print 'var iq=function(){ window.location.assign(document.getElementById("epuri").value+"?query="+encodeURIComponent(editor.getValue())); }';
    if ($KEY_VAL{endpoint} =~ "https://query.wikidata.org/") {
        print "var iq=function(){ window.location.assign('$KEY_VAL{endpoint}#'+encodeURIComponent(editor.getValue())); }";
    } else {
        print "var iq=function(){ window.location.assign('$KEY_VAL{endpoint}?query='+encodeURIComponent(editor.getValue())); }";
    }
    print '</script>';

print <<HERE2;
<br>
<br>
</div>
</body>
</html>
HERE2

} else {
    print "Content-type: text/plain\n\n";
    print $CONTENT;
}

################################################################################
### Function ###################################################################
################################################################################
sub parse_ini_file {
    my ($ini_file, $r_val) = @_;

    if (-f $ini_file) {
	open(FILE, $ini_file) || die;
	while (<FILE>) {
	    chomp;
	    if (/^(\S+)\s+(\S.+)/) {
		my ($key, $val) = ($1, $2);
		${$r_val}{$key} = $val;
	    }
	}
	close(FILE);
    }
}
