#param extended defaultOrganism
#param default null
SELECT ?taxon ?ref_org_code
WHERE {
    ?ref_org ^orth:organism mbgdr:$1 ;
        dct:identifier ?ref_org_code ;
        mbgd:inTaxon ?taxon ;
        dct:issued ?min_date .
    {
        SELECT ?taxon (min(?date) AS ?min_date)
        WHERE {
            ?org ^orth:organism mbgdr:$1 ;
                  mbgd:inTaxon ?taxon ;
                  dct:issued ?date .
        }
    }
    {
        SELECT ?taxon
        WHERE {
            mbgdr:$1 orth:organism/mbgd:inTaxon ?taxon .
            MINUS { ?taxon mbgd:$2 ?default_org .}
        }
    }
}
